name: create-test

on:
  create:
    branches: test/**

jobs:
  work-start:
    runs-on: ubuntu-latest
    env:
      REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
      HEAD_REF: ${{ github.ref }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}

      - name: start commit
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git commit --allow-empty -m "[${HEAD_REF#*test/}]: 作成" && git push ${REPO} HEAD:${HEAD_REF}

      - name: create pull request
        if: success()
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          ref: ${HEAD_REF#*test/}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: ref + ': 作成,'
              head: 'action:' + ref,
              base: "master"
            });
