name: create-test

on:
  create:
    branches: test/**

jobs:
  work-start:
    runs-on: ubuntu-latest
    env:
      REPO: https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git
      HEAD_REF: ${{ github.ref }}
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.ref}}

      - name: start commit
        run: |
          git commit --allow-empty -m "[${HEAD_REF#*test/}]: 作成" && git push ${REPO} HEAD:${HEAD_REF} || true

      - name: create pull request
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: "[${HEAD_REF#*test/}]: 作成",
              head: ${HEAD_REF},
              base: "master"
            });
